import { Router } from 'express';
import { authenticateJWT, requireRole } from '../../core/authMiddleware.js';
import * as a from './admin.controller.js';

const router = Router();
router.use(authenticateJWT, requireRole('ADMIN'));
router.get('/dashboard', a.dashboard);
router.get('/analytics', a.analytics);
router.get('/orders', a.orders);
router.get('/orders/:id', a.orderDetail);
router.patch('/orders/:id/status', a.updateOrderStatus);
router.get('/products', a.products);
router.post('/products', a.saveProduct);
router.post('/products/publish', a.publishProduct);
router.put('/products/:id', a.saveProduct);
router.patch('/products/:id/web-status', a.toggleProductWebStatus);
router.delete('/products/:id', a.archiveProduct);
router.post('/orders/:id/shipment', a.createOrUpdateShipment);

router.post('/categories', a.createCategory);
router.delete('/categories/:id', a.deleteCategory);
router.get('/inventory', a.inventory);
router.get('/inventory/logs', a.inventoryLogs);
router.post('/inventory/:variantId/adjust', a.adjustInventory);
router.get('/batches', a.batches);
router.post('/batches', a.createBatch);
router.get('/vouchers', a.warehouseVouchers);
router.get('/vouchers/:id', a.warehouseVoucher);
router.post('/vouchers/multi-item', a.createWarehouseVoucher);
router.get('/mobile/home', a.mobileHome);
router.get('/reviews', a.reviews);
router.patch('/reviews/:id', a.moderateReview);
router.post('/reviews/:id/replies', a.replyReview);
router.get('/testimonials', a.testimonials);
router.patch('/testimonials/:id', a.moderateTestimonial);
export default router;
